variable "ext_alb_name" {}
variable "int_alb_name" {}
variable "s3_name" {}
variable "environment" {}
variable "idle_timeout" {}
variable "alb_type" {}
variable "deletion_protection" {}
variable "ext_alb_prefix" {}
variable "int_alb_prefix" {}
variable "ext_alb_listener_port" {}
variable "ext_alb_listener_protocol" {}
variable "target_group_name" {}
variable "vpc_id" {}
variable "health_check_path" {}
variable "health_check_port" {}
variable "vpc_state_bucket" {}
variable "vpc_state_key" {}
variable "region" {}